#ifndef CONFIG_HPP
#define CONFIG_HPP


//#define SMLGR_CONFIG_DEFAULT_INV_ADDR "172.16.83.2"
#define SMLGR_CONFIG_DEFAULT_INV_ADDR "127.0.0.1"
#define SMLGR_CONFIG_DEFAULT_INV_PORT 12345
#define SMLGR_CONFIG_DEFAULT_INV_NUM 1

#define SMLGR_CONFIG_DEFAULT_QUERY "UDC;IDC;UL1;IL1;PAC;PRL;TKK;TNF;KDY;KLD"
#define SMLGR_CONFIG_DEFAULT_INTERVAL 50

#define SMLGR_CONFIG_DEFAULT_SQL_ADDR "127.0.0.1"
#define SMLGR_CONFIG_DEFAULT_SQL_PORT 5432
#define SMLGR_CONFIG_DEFAULT_SQL_USERNAME "smlgr"
#define SMLGR_CONFIG_DEFAULT_SQL_PASSWORD "smlgr"
#define SMLGR_CONFIG_DEFAULT_SQL_DATABASE "smlgr"

#endif // CONFIG_HPP
